# Generated by Django 3.0.1 on 2021-06-11 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0034_auto_20210610_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lang_graphs',
            name='cpp',
        ),
        migrations.RemoveField(
            model_name='lang_graphs',
            name='java',
        ),
        migrations.RemoveField(
            model_name='lang_graphs',
            name='js',
        ),
        migrations.RemoveField(
            model_name='lang_graphs',
            name='php',
        ),
        migrations.RemoveField(
            model_name='lang_graphs',
            name='py',
        ),
        migrations.AddField(
            model_name='lang_graphs',
            name='name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lang_graphs',
            name='val',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='bpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybl.Bpost'),
        ),
    ]
