# Generated by Django 3.0.1 on 2021-06-11 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0035_auto_20210611_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lang_graphs',
            name='val',
        ),
        migrations.AddField(
            model_name='lang_graphs',
            name='res_vac',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='bpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybl.Bpost'),
        ),
    ]
