# Generated by Django 3.0.1 on 2021-07-22 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0036_auto_20210611_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='bvsp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='copper',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='gdaxi',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='sz',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='wheat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='bpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybl.Bpost'),
        ),
    ]
