# Generated by Django 3.0.1 on 2021-07-22 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0037_auto_20210722_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='copper',
        ),
        migrations.AlterField(
            model_name='comment',
            name='bpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybl.Bpost'),
        ),
    ]
