# Generated by Django 3.0.1 on 2021-07-22 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0039_auto_20210722_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='bsesn',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='bpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybl.Bpost'),
        ),
    ]
