# Generated by Django 3.2.7 on 2022-05-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0043_auto_20210908_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lang_graphs',
            old_name='res_vac',
            new_name='val',
        ),
    ]
