# Generated by Django 3.2.7 on 2023-08-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0043_auto_20210908_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bpost',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='bpost',
        ),
        migrations.DeleteModel(
            name='Lang_graphs',
        ),
        migrations.DeleteModel(
            name='bPost',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
