# Generated by Django 3.1.2 on 2024-10-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0044_auto_20230807_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='sz',
        ),
    ]
