# Generated by Django 3.2.7 on 2022-06-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0044_rename_res_vac_lang_graphs_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='usd',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
