# Generated by Django 3.1.2 on 2024-10-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0045_remove_ticker_sz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='cop',
            new_name='copper',
        ),
    ]
